// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-design/CampoAberto.tsx": () => import("../components/mockups/home-design/CampoAberto.tsx"),
  "./components/mockups/home-design/Raiz.tsx": () => import("../components/mockups/home-design/Raiz.tsx"),
  "./components/mockups/home-design/TerraFirme.tsx": () => import("../components/mockups/home-design/TerraFirme.tsx")
};
